### ISSUE TITLE
Suggested usage with more complex link styles

### ISSUE THREAD

**Issue by timkelty** [suitcss/utils-link#8]
In it's current state, `utils-link` pretty much seems to deal with just text decoration.
I'm curious what you might suggest in a situation where you had more base styles on your `a` elements.

e.g.

``` css
a {
  color: red;
  border-bottom: 1px solid black;
  background: whitesmoke;
}
```

In this case would you just not use `utils-link` classes at all, or would you redefine them to reset the additional properties?
